---
title: "About ReModel"
image: images/logo_yellow.svg
page-layout: full
format: 
  html:
    toc: true
---

## ReModel aims

Building a simulation model from scratch is a time-consuming and resource-intensive process. ReModel aims to make it easier for healthcare analysts to read, run, and reuse existing open simulation models. We recognise that within healthcare there is a potential to reuse existing models because many of the problems faced by healthcare systems are similar as are many of the pathways experienced by patients. ReModel is a project that aims to make it easier to read, run, and reuse open simulation models.

Our goal is to empower people within the NHS to:

- run open source simulation models on their own machines
- critique/assess/evaluate simulation models with their pros and cons
- repurpose existing simulation models for their own use cases

## How does ReModel work?

[See how ReModel works](join-us/index.qmd#how-remodel-works) for further details on how sessions will run. Whilst our target audience is NHS analysts we welcome registrations from non-NHS analysts. Spaces will be capped to 15 places per session and places will be prioritised for NHS analysts.

## How do I join?

[Register for ReModel](join-us/index.qmd#register-for-remodel).

## How we are funded

ReModel has been funded in 25/26 as part of the national Strategic Commissioning Intelligence Centre (SCIC).  

Simulation modelling can be effectively used in strategic commissioning by:

- Analysing complex systems: It allows organizations to evaluate different scenarios and make data-driven decisions, which is crucial for strategic planning in commissioning.
- Identifying resource needs: Simulation modelling helps in understanding the current state of health services and identifying underserved communities, enabling better allocation of resources.
- Evaluating service impacts: It allows for the assessment of the impact of various service changes on population health and resource utilization, ensuring that commissioning decisions are evidence-based.
- Supporting economic evaluation: By analysing the economic return on investment for interventions, simulation modelling aids in prioritizing services and ensuring that resources are used efficiently.
- Facilitating transparency: It promotes transparency in decision-making processes, allowing stakeholders to understand the rationale behind commissioning decisions.
